[package]
name = "consensus"
version = "0.1.0"
authors = ["Adam Wick <awick@uhsure.com>"]

[dependencies]
chrono        = "^0.4.0"
nom           = "^3.1.0"
ring          = "^0.12.1"
simple_rsa    = { path = "../simple_rsa" }
parsing_utils = { path = "../parsing_utils" }
