[package]
name = "tor_config"
version = "0.1.0"
authors = ["awick"]

[dependencies]
chrono       = "^0.4.0"
fern         = "^0.4.0"
log          = "^0.3.0"
serde        = "^1.0.11"
serde_derive = "^1.0.11"
toml         = "^0.4.2"
xdg          = "^2.1.0"
